---
- name: Installing Git if it is not installed
  hosts: HostMachine1
  tasks:
    - name: Checking if git is installed or not
      tags: check
      shell: git --version
      register: gitVariable
      ignore_errors: true

    - name: Printing if git is not installed
      tags: print
      when: gitVariable is not defined or 'rc' not in gitVariable or gitVariable.rc != 0
      debug:
        msg: "Git is not installed"

    - name: Git is already installed
      tags: check
      when: gitVariable is defined and 'rc' in gitVariable and gitVariable.rc == 0
      debug: 
        msg: "Git is already installed with version {{ gitVariable.stdout }}"

    - name: Install Git using APT package manager
      tags: install
      when: gitVariable is not defined or 'rc' not in gitVariable or gitVariable.rc != 0
      apt:
        name: git
        state: present
      register: status

    - name: Get Git Version
      tags: print
      shell: git --version
      register: gitStatus

    - name: Printing Git is successfully installed
      tags: print
      when: gitStatus is defined and 'rc' in gitStatus and gitStatus.rc == 0
      debug:
        msg: "Git is installed with version {{ gitStatus.stdout }} and installation status is {{ status }}"
...

# ansible-playbook checkAndInstallUsingTags.yml --tags 'check'